import type { TranscriptEntry } from "@/types/transcript";
import type { MeetingSummary } from "@/types/transcript";

// ─────────────────────────────────────────────────────────────────────────────
// Transcript 포맷팅 및 다운로드 유틸리티
// ─────────────────────────────────────────────────────────────────────────────

/**
 * transcript 엔트리 목록을 텍스트 파일 형식으로 포맷팅
 * 형식: [HH:MM:SS] 발화자: 텍스트
 */
export function formatTranscriptForDownload(
  entries: TranscriptEntry[],
): string {
  if (entries.length === 0) {
    return "자막이 없습니다.";
  }

  const lines = entries.map((entry) => {
    const time = new Date(entry.timestamp).toISOString().slice(11, 19); // HH:MM:SS
    return `[${time}] ${entry.speakerName}: ${entry.text}`;
  });

  return lines.join("\n");
}

/**
 * 회의 요약을 마크다운 파일 형식으로 포맷팅
 */
export function formatSummaryForDownload(
  summary: MeetingSummary,
): string {
  const date = new Date(summary.generatedAt).toLocaleString("ko-KR");
  const duration = Math.round(summary.duration / 60000); // 분 단위

  const lines: string[] = [
    "# 회의 요약",
    "",
    `**생성 일시**: ${date}`,
    `**회의 시간**: ${duration}분`,
    `**참가자**: ${summary.participantNames.join(", ")}`,
    "",
    "## 요약",
    "",
    summary.summary,
    "",
  ];

  if (summary.keyPoints.length > 0) {
    lines.push("## 핵심 포인트", "");
    summary.keyPoints.forEach((point) => {
      lines.push(`- ${point}`);
    });
    lines.push("");
  }

  if (summary.actionItems.length > 0) {
    lines.push("## 액션 아이템", "");
    summary.actionItems.forEach((item) => {
      lines.push(`- ${item}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by Roomly_");

  return lines.join("\n");
}

/**
 * 텍스트를 파일로 다운로드
 */
export function downloadAsFile(
  content: string,
  filename: string,
  mimeType: string = "text/plain",
): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();

  // cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 타임스탬프를 파일명에 사용할 수 있는 형식으로 변환
 * 예: 20260402_143025
 */
export function getTimestampForFilename(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  const hours = String(now.getHours()).padStart(2, "0");
  const minutes = String(now.getMinutes()).padStart(2, "0");
  const seconds = String(now.getSeconds()).padStart(2, "0");

  return `${year}${month}${day}_${hours}${minutes}${seconds}`;
}

/**
 * transcript를 .txt 파일로 다운로드
 */
export function downloadTranscript(
  entries: TranscriptEntry[],
  roomId: string,
): void {
  const content = formatTranscriptForDownload(entries);
  const timestamp = getTimestampForFilename();
  const filename = `roomly_transcript_${roomId}_${timestamp}.txt`;
  downloadAsFile(content, filename, "text/plain");
}

/**
 * 요약을 .md 파일로 다운로드
 */
export function downloadSummary(
  summary: MeetingSummary,
  roomId: string,
): void {
  const content = formatSummaryForDownload(summary);
  const timestamp = getTimestampForFilename();
  const filename = `roomly_summary_${roomId}_${timestamp}.md`;
  downloadAsFile(content, filename, "text/markdown");
}
